name: optimizing_bird_classification
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - matplotlib
  - notebook
  - numpy
  - opencv
  - pandas
  - pip
  - plotly
  - scikit-learn
  - scipy
  - seaborn
  - tqdm
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - torchaudio
  
  - pip:
      - kornia
      - ultralytics
      - xformers
      - schedulefree
      
